env:
  node: true
  commonjs: true
  es2020: true
  jest/globals: true
extends:
  - standard
  - plugin:jest/all
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/standard
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
plugins:
  - "@typescript-eslint"
  - eslint-plugin-tsdoc
  - jest
rules:
  tsdoc/syntax: warn
ignorePatterns:
  - "dist/*"
