env:
  node: true
  commonjs: true
  es2020: true
  jest/globals: true
extends:
  - standard
  - plugin:jest/all
  - prettier
  - prettier/standard
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
plugins:
  - "@typescript-eslint"
  - jest
rules: {}
