---
branches:
  - main
  - name: develop
    prerelease: true

plugins:
  - "@semantic-release/github"
  - "@semantic-release/commit-analyzer":
      preset: conventionalcommits
  - "@semantic-release/release-notes-generator"
