---
name: Run taskcat tests
author: Shahrad Rezaei
description: |
  The unofficial GitHub Action to run taskcat tests and validate your AWS
  CloudFormation templates

branding:
  icon: check-square
  color: green

inputs:
  commands:
    description: |
      Command, subcommands, and arguments to pass to taskcat. Should be
      formatted as "[args] <command> [args] [subcommand] [args]". The taskcat
      invocation itself is already handled by the action-no need to prefix the
      command with "taskcat".
    required: true
  update_taskcat:
    description: |
      If set to "true", this action will update taskcat its the latest version
      before running tests.
    required: false

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.commands }}
  post-entrypoint: /dist/index.js
