name: CI workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"

permissions:
  checks: write
  issues: write
  contents: write

jobs:
  e2e-default:
    name: End-to-end tests - default
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        id: aws-credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1
      - name: Invoke "taskcat test run"
        uses: ./
        with:
          commands: test run --lint-disable --project-root ./e2e/resources/default

  e2e-update:
    name: End-to-end tests - update taskcat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1
      - name: Invoke "taskcat test run"
        uses: ./
        with:
          commands: test run --lint-disable --project-root ./e2e/resources/default
          update_taskcat: true

  e2e-lint-update:
    name: End-to-end tests - update taskcat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1
      - name: Invoke "taskcat test run"
        uses: ./
        with:
          commands: test run --lint-disable --project-root ./e2e/resources/default
          update_taskcat: true
          update_cfn_lint: true

  e2e-v1-default:
    name: End-to-end tests - @v1 - default
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1
      - name: Invoke "taskcat test run"
        uses: ShahradR/action-taskcat@v1
        with:
          commands: test run --lint-disable --project-root ./e2e/resources/default

  e2e-v1-update:
    name: End-to-end tests - @v1 - update taskcat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1
      - name: Invoke "taskcat test run --lint-disable"
        uses: ShahradR/action-taskcat@v1
        with:
          commands: test run --project-root ./e2e/resources/default
          update_taskcat: true

  e2e-v1-lint-update:
    name: End-to-end tests - @v1 - update taskcat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1
      - name: Invoke "taskcat test run --lint-disable"
        uses: ShahradR/action-taskcat@v1
        with:
          commands: test run --project-root ./e2e/resources/default
          update_taskcat: true
          update_cfn_lint: true

  e2e-v2-default:
    name: End-to-end tests - @v2 - default
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1
      - name: Invoke "taskcat test run --lint-disable"
        uses: ShahradR/action-taskcat@v2
        with:
          commands: test run --project-root ./e2e/resources/default

  e2e-v2-update:
    name: End-to-end tests - @v2 - update taskcat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1
      - name: Invoke "taskcat test run --lint-disable"
        uses: ShahradR/action-taskcat@v2
        with:
          commands: test run --project-root ./e2e/resources/default
          update_taskcat: true

  e2e-v2-lint-update:
    name: End-to-end tests - @v2 - update taskcat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1
      - name: Invoke "taskcat test run --lint-disable"
        uses: ShahradR/action-taskcat@v2
        with:
          commands: test run --project-root ./e2e/resources/default
          update_taskcat: true
          update_cfn_lint: true
