name: Tests

on: [push, pull_request]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install nektos/act
        run: curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run the Maven verify phase
        run: mvn -B verify --file pom.xml
